---
title: "個人投手成績（規定投球回以上）"
output: 
  flexdashboard::flex_dashboard:
    theme: lumen
    orientation: rows
#    vertical_layout: fill
    vertical_layout: scroll
    navbar:
      - { title: "Home", href: "https://hokmts23.netlify.app/en/2022npb/"}
    social: [ "twitter","menu"]
#default”, “bootstrap”, “cerulean”, “cosmo”, “darkly”, “flatly”, “journal”, “lumen”, “paper”, #“readable”, “sandstone”, “simplex”, “spacelab”, “united”, “yeti”
---

```{r setup, include=FALSE}
library(flexdashboard)
library("rvest")
library("dplyr")
library("tidyverse")
library("openxlsx")
library("ggplot2")
library("patchwork")
library("knitr")
library("kableExtra")
library("tidyverse")
library("cowplot")
library("gridExtra")
library("gganimate")
#library("transformr")
library("gifski")
library("gt")
library("DT")
library("readxl")
# data load & pacific central data merge
pitp_data<-  read_xlsx("~/Public/baseball/2022/02data/02league/pit_p_2022pl.xlsx",
                        sheet = 'Sheet1')
```


row {data-height=300}
-------------------------------------

### 

```{r }
valueBox(paste("summary"))
```

### 

```{r}
summary(pitp_data$防御率[1:9]) %>% as.array(.) %>% 
as.data.frame(.) %>% 
  rename(.data = . ,　"防御率" = "Var1") %>%
  rename(.data = . ,　" " = "Freq") %>%
  format(., digits = 4) %>%
  kbl(.) %>% kable_minimal(full_width = F)
```

### 

```{r}
summary(pitp_data$FIP[1:9]) %>% as.array(.) %>% 
as.data.frame(.) %>% 
  rename(.data = . ,　"FIP" = "Var1") %>%
  rename(.data = . ,　" " = "Freq") %>%
  format(., digits = 4) %>%
  kbl(.) %>% kable_minimal(full_width = F)
```

### 

```{r}
summary(pitp_data$BABIP[1:9]) %>% as.array(.) %>% 
as.data.frame(.) %>% 
  rename(.data = . ,　"BABIP" = "Var1") %>%
  rename(.data = . ,　" " = "Freq") %>%
  format(., digits = 3) %>%
  kbl(.) %>% kable_minimal(full_width = F)
```

### 

```{r}
summary(pitp_data$K9[1:9]) %>% as.array(.) %>% 
as.data.frame(.) %>% 
  rename(.data = . ,　"K9" = "Var1") %>%
  rename(.data = . ,　" " = "Freq") %>%
  format(., digits = 4) %>%
  kbl(.) %>% kable_minimal(full_width = F)
```

### 

```{r}
summary(pitp_data$BB9[1:9]) %>% as.array(.) %>% 
as.data.frame(.) %>% 
  rename(.data = . ,　"BB9" = "Var1") %>%
  rename(.data = . ,　" " = "Freq") %>%
  format(., digits = 3) %>%
  kbl(.) %>% kable_minimal(full_width = F)
```

### 

```{r}
summary(pitp_data$HR9[1:9]) %>% as.array(.) %>% 
as.data.frame(.) %>% 
  rename(.data = . ,　"HR9" = "Var1") %>%
  rename(.data = . ,　" " = "Freq") %>%
  format(., digits = 3) %>%
  kbl(.) %>% kable_minimal(full_width = F)
```

### 

```{r}
summary(pitp_data$H9[1:9]) %>% as.array(.) %>% 
as.data.frame(.) %>% 
  rename(.data = . ,　"H9" = "Var1") %>%
  rename(.data = . ,　" " = "Freq") %>%
  format(., digits = 4) %>%
  kbl(.) %>% kable_minimal(full_width = F)
```

### 

```{r}
summary(pitp_data$LOB[1:9]) %>% as.array(.) %>% 
as.data.frame(.) %>% 
  rename(.data = . ,　"LOB" = "Var1") %>%
  rename(.data = . ,　" " = "Freq") %>%
  format(., digits = 3) %>%
  kbl(.) %>% kable_minimal(full_width = F)
```

### 

```{r}
summary(pitp_data$`K-BB%`[1:9]) %>% as.array(.) %>% 
as.data.frame(.) %>% 
  rename(.data = . ,　"K-BB%" = "Var1") %>%
  rename(.data = . ,　" " = "Freq") %>%
  format(., digits = 2) %>%
  kbl(.) %>% kable_minimal(full_width = F)
```

## row

### ORIX Buffaloes

```{r}
valueBox(paste(pitp_data$投手[1]))
```

### 防御率

```{r}
gauge(pitp_data$防御率[1], min = 0, max = 5, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,2.010), warning = c(2.011,2.950), danger = c(2.951,99)
))
```

### FIP

```{r}
gauge(pitp_data$FIP[1], min = 0, max = 5,  abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,2.707), warning = c(2.708,3.019), danger = c(3.02,99)
))
```

### BABIP

```{r}
gauge(pitp_data$BABIP[1], min = 0, max = 0.5, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,0.265), warning = c(0.266,0.277), danger = c(0.278,99)
))
```

### K9

```{r}
gauge(pitp_data$K9[1], min = 0, max = 20, abbreviateDecimals = 3, 
      gaugeSectors(success = c(6.958,99), warning = c(6.504,6.957), danger = c(0,6.503)
))
```

### BB9

```{r}
gauge(pitp_data$BB9[1], min = 0, max = 5, abbreviateDecimals = 2, 
      gaugeSectors(success = c(0,1.824), warning = c(1.825,2.623), danger = c(2.624,99)
))
```

### HR9

```{r}
gauge(pitp_data$HR9[1], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,0.438), warning = c(0.439,0.551), danger = c(0.552,99)
))
```

### H9

```{r}
gauge(pitp_data$H9[1], min = 0, max = 15, abbreviateDecimals = 2, 
      gaugeSectors(success = c(0,7.592), warning = c(7.593,7.869), danger = c(7.870,99)
))
```

### LOB

```{r}
gauge(pitp_data$LOB[1], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0.761,99), warning = c(0.752,0.760), danger = c(0,0.751)
))
```

### K-BB%

```{r}
gauge(pitp_data$`K-BB%`[1], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0.145,99), warning = c(0.110,0.144), danger = c(0,0.109)
))
```

------------------------------------------------------------------------

## row

### Fukuoka SoftBank Hawks

```{r}
valueBox(paste(pitp_data$投手[2]))
```

### 防御率

```{r}
gauge(pitp_data$防御率[2], min = 0, max = 5, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,2.010), warning = c(2.011,2.950), danger = c(2.951,99)
))
```

### FIP

```{r}
gauge(pitp_data$FIP[2], min = 0, max = 5,  abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,2.707), warning = c(2.708,3.019), danger = c(3.02,99)
))
```

### BABIP

```{r}
gauge(pitp_data$BABIP[2], min = 0, max = 0.5, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,0.265), warning = c(0.266,0.277), danger = c(0.278,99)
))
```

### K9

```{r}
gauge(pitp_data$K9[2], min = 0, max = 20, abbreviateDecimals = 3, 
      gaugeSectors(success = c(6.958,99), warning = c(6.504,6.957), danger = c(0,6.503)
))
```

### BB9

```{r}
gauge(pitp_data$BB9[2], min = 0, max = 5, abbreviateDecimals = 2, 
      gaugeSectors(success = c(0,1.824), warning = c(1.825,2.623), danger = c(2.624,99)
))
```

### HR9

```{r}
gauge(pitp_data$HR9[2], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,0.438), warning = c(0.439,0.551), danger = c(0.552,99)
))
```

### H9

```{r}
gauge(pitp_data$H9[2], min = 0, max = 15, abbreviateDecimals = 2, 
      gaugeSectors(success = c(0,7.592), warning = c(7.593,7.869), danger = c(7.870,99)
))
```

### LOB

```{r}
gauge(pitp_data$LOB[2], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0.761,99), warning = c(0.752,0.760), danger = c(0,0.751)
))
```

### K-BB%

```{r}
gauge(pitp_data$`K-BB%`[2], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0.145,99), warning = c(0.110,0.144), danger = c(0,0.109)
))
```

------------------------------------------------------------------------

## row

### Hokkaido Nippon-Ham Fighters

```{r}
valueBox(paste(pitp_data$投手[3]))
```

### 防御率

```{r}
gauge(pitp_data$防御率[3], min = 0, max = 5, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,2.010), warning = c(2.011,2.950), danger = c(2.951,99)
))
```

### FIP

```{r}
gauge(pitp_data$FIP[3], min = 0, max = 5,  abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,2.707), warning = c(2.708,3.019), danger = c(3.02,99)
))
```

### BABIP

```{r}
gauge(pitp_data$BABIP[3], min = 0, max = 0.5, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,0.265), warning = c(0.266,0.277), danger = c(0.278,99)
))
```

### K9

```{r}
gauge(pitp_data$K9[3], min = 0, max = 20, abbreviateDecimals = 3, 
      gaugeSectors(success = c(6.958,99), warning = c(6.504,6.957), danger = c(0,6.503)
))
```

### BB9

```{r}
gauge(pitp_data$BB9[3], min = 0, max = 5, abbreviateDecimals = 2, 
      gaugeSectors(success = c(0,1.824), warning = c(1.825,2.623), danger = c(2.624,99)
))
```

### HR9

```{r}
gauge(pitp_data$HR9[3], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,0.438), warning = c(0.439,0.551), danger = c(0.552,99)
))
```

### H9

```{r}
gauge(pitp_data$H9[3], min = 0, max = 15, abbreviateDecimals = 2, 
      gaugeSectors(success = c(0,7.592), warning = c(7.593,7.869), danger = c(7.870,99)
))
```

### LOB

```{r}
gauge(pitp_data$LOB[3], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0.761,99), warning = c(0.752,0.760), danger = c(0,0.751)
))
```

### K-BB%

```{r}
gauge(pitp_data$`K-BB%`[3], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0.145,99), warning = c(0.110,0.144), danger = c(0,0.109)
))
```

------------------------------------------------------------------------

## row

### Saitama Seibu Lions

```{r}
valueBox(paste(pitp_data$投手[4]))
```

### 防御率

```{r}
gauge(pitp_data$防御率[4], min = 0, max = 5, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,2.010), warning = c(2.011,2.950), danger = c(2.951,99)
))
```

### FIP

```{r}
gauge(pitp_data$FIP[4], min = 0, max = 5,  abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,2.707), warning = c(2.708,3.019), danger = c(3.02,99)
))
```

### BABIP

```{r}
gauge(pitp_data$BABIP[4], min = 0, max = 0.5, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,0.265), warning = c(0.266,0.277), danger = c(0.278,99)
))
```

### K9

```{r}
gauge(pitp_data$K9[4], min = 0, max = 20, abbreviateDecimals = 3, 
      gaugeSectors(success = c(6.958,99), warning = c(6.504,6.957), danger = c(0,6.503)
))
```

### BB9

```{r}
gauge(pitp_data$BB9[4], min = 0, max = 5, abbreviateDecimals = 2, 
      gaugeSectors(success = c(0,1.824), warning = c(1.825,2.623), danger = c(2.624,99)
))
```

### HR9

```{r}
gauge(pitp_data$HR9[4], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,0.438), warning = c(0.439,0.551), danger = c(0.552,99)
))
```

### H9

```{r}
gauge(pitp_data$H9[4], min = 0, max = 15, abbreviateDecimals = 2, 
      gaugeSectors(success = c(0,7.592), warning = c(7.593,7.869), danger = c(7.870,99)
))
```

### LOB

```{r}
gauge(pitp_data$LOB[4], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0.761,99), warning = c(0.752,0.760), danger = c(0,0.751)
))
```

### K-BB%

```{r}
gauge(pitp_data$`K-BB%`[4], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0.145,99), warning = c(0.110,0.144), danger = c(0,0.109)
))
```

------------------------------------------------------------------------

## row

### Hokkaido Nippon-Ham Fighters

```{r}
valueBox(paste(pitp_data$投手[5]))
```

### 防御率

```{r}
gauge(pitp_data$防御率[5], min = 0, max = 5, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,2.010), warning = c(2.011,2.950), danger = c(2.951,99)
))
```

### FIP

```{r}
gauge(pitp_data$FIP[5], min = 0, max = 5,  abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,2.707), warning = c(2.708,3.019), danger = c(3.02,99)
))
```

### BABIP

```{r}
gauge(pitp_data$BABIP[5], min = 0, max = 0.5, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,0.265), warning = c(0.266,0.277), danger = c(0.278,99)
))
```

### K9

```{r}
gauge(pitp_data$K9[5], min = 0, max = 20, abbreviateDecimals = 3, 
      gaugeSectors(success = c(6.958,99), warning = c(6.504,6.957), danger = c(0,6.503)
))
```

### BB9

```{r}
gauge(pitp_data$BB9[5], min = 0, max = 5, abbreviateDecimals = 2, 
      gaugeSectors(success = c(0,1.824), warning = c(1.825,2.623), danger = c(2.624,99)
))
```

### HR9

```{r}
gauge(pitp_data$HR9[5], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,0.438), warning = c(0.439,0.551), danger = c(0.552,99)
))
```

### H9

```{r}
gauge(pitp_data$H9[5], min = 0, max = 15, abbreviateDecimals = 2, 
      gaugeSectors(success = c(0,7.592), warning = c(7.593,7.869), danger = c(7.870,99)
))
```

### LOB

```{r}
gauge(pitp_data$LOB[5], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0.761,99), warning = c(0.752,0.760), danger = c(0,0.751)
))
```

### K-BB%

```{r}
gauge(pitp_data$`K-BB%`[5], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0.145,99), warning = c(0.110,0.144), danger = c(0,0.109)
))
```

------------------------------------------------------------------------

## row

### Chiba Lotte Marines

```{r}
valueBox(paste(pitp_data$投手[6]))
```

### 防御率

```{r}
gauge(pitp_data$防御率[6], min = 0, max = 5, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,2.010), warning = c(2.011,2.950), danger = c(2.951,99)
))
```

### FIP

```{r}
gauge(pitp_data$FIP[6], min = 0, max = 5,  abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,2.707), warning = c(2.708,3.019), danger = c(3.02,99)
))
```

### BABIP

```{r}
gauge(pitp_data$BABIP[6], min = 0, max = 0.5, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,0.265), warning = c(0.266,0.277), danger = c(0.278,99)
))
```

### K9

```{r}
gauge(pitp_data$K9[6], min = 0, max = 20, abbreviateDecimals = 3, 
      gaugeSectors(success = c(6.958,99), warning = c(6.504,6.957), danger = c(0,6.503)
))
```

### BB9

```{r}
gauge(pitp_data$BB9[6], min = 0, max = 5, abbreviateDecimals = 2, 
      gaugeSectors(success = c(0,1.824), warning = c(1.825,2.623), danger = c(2.624,99)
))
```

### HR9

```{r}
gauge(pitp_data$HR9[6], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,0.438), warning = c(0.439,0.551), danger = c(0.552,99)
))
```

### H9

```{r}
gauge(pitp_data$H9[6], min = 0, max = 15, abbreviateDecimals = 2, 
      gaugeSectors(success = c(0,7.592), warning = c(7.593,7.869), danger = c(7.870,99)
))
```

### LOB

```{r}
gauge(pitp_data$LOB[6], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0.761,99), warning = c(0.752,0.760), danger = c(0,0.751)
))
```

### K-BB%

```{r}
gauge(pitp_data$`K-BB%`[6], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0.145,99), warning = c(0.110,0.144), danger = c(0,0.109)
))
```

------------------------------------------------------------------------

## row

### ORIX Buffaloes

```{r}
valueBox(paste(pitp_data$投手[7]))
```

### 防御率

```{r}
gauge(pitp_data$防御率[7], min = 0, max = 5, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,2.010), warning = c(2.011,2.950), danger = c(2.951,99)
))
```

### FIP

```{r}
gauge(pitp_data$FIP[7], min = 0, max = 5,  abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,2.707), warning = c(2.708,3.019), danger = c(3.02,99)
))
```

### BABIP

```{r}
gauge(pitp_data$BABIP[7], min = 0, max = 0.5, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,0.265), warning = c(0.266,0.277), danger = c(0.278,99)
))
```

### K9

```{r}
gauge(pitp_data$K9[7], min = 0, max = 20, abbreviateDecimals = 3, 
      gaugeSectors(success = c(6.958,99), warning = c(6.504,6.957), danger = c(0,6.503)
))
```

### BB9

```{r}
gauge(pitp_data$BB9[7], min = 0, max = 5, abbreviateDecimals = 2, 
      gaugeSectors(success = c(0,1.824), warning = c(1.825,2.623), danger = c(2.624,99)
))
```

### HR9

```{r}
gauge(pitp_data$HR9[7], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,0.438), warning = c(0.439,0.551), danger = c(0.552,99)
))
```

### H9

```{r}
gauge(pitp_data$H9[7], min = 0, max = 15, abbreviateDecimals = 2, 
      gaugeSectors(success = c(0,7.592), warning = c(7.593,7.869), danger = c(7.870,99)
))
```

### LOB

```{r}
gauge(pitp_data$LOB[7], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0.761,99), warning = c(0.752,0.760), danger = c(0,0.751)
))
```

### K-BB%

```{r}
gauge(pitp_data$`K-BB%`[7], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0.145,99), warning = c(0.110,0.144), danger = c(0,0.109)
))
```

------------------------------------------------------------------------

## row

### Tohoku Rakuten Golden Eagles

```{r}
valueBox(paste(pitp_data$投手[8]))
```

### 防御率

```{r}
gauge(pitp_data$防御率[8], min = 0, max = 5, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,2.010), warning = c(2.011,2.950), danger = c(2.951,99)
))
```

### FIP

```{r}
gauge(pitp_data$FIP[8], min = 0, max = 5,  abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,2.707), warning = c(2.708,3.019), danger = c(3.02,99)
))
```

### BABIP

```{r}
gauge(pitp_data$BABIP[8], min = 0, max = 0.5, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,0.265), warning = c(0.266,0.277), danger = c(0.278,99)
))
```

### K9

```{r}
gauge(pitp_data$K9[8], min = 0, max = 20, abbreviateDecimals = 3, 
      gaugeSectors(success = c(6.958,99), warning = c(6.504,6.957), danger = c(0,6.503)
))
```

### BB9

```{r}
gauge(pitp_data$BB9[8], min = 0, max = 5, abbreviateDecimals = 2, 
      gaugeSectors(success = c(0,1.824), warning = c(1.825,2.623), danger = c(2.624,99)
))
```

### HR9

```{r}
gauge(pitp_data$HR9[8], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,0.438), warning = c(0.439,0.551), danger = c(0.552,99)
))
```

### H9

```{r}
gauge(pitp_data$H9[8], min = 0, max = 15, abbreviateDecimals = 2, 
      gaugeSectors(success = c(0,7.592), warning = c(7.593,7.869), danger = c(7.870,99)
))
```

### LOB

```{r}
gauge(pitp_data$LOB[8], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0.761,99), warning = c(0.752,0.760), danger = c(0,0.751)
))
```

### K-BB%

```{r}
gauge(pitp_data$`K-BB%`[8], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0.145,99), warning = c(0.110,0.144), danger = c(0,0.109)
))
```

------------------------------------------------------------------------

## row

### Hokkaido Nippon-Ham Fighters

```{r}
valueBox(paste(pitp_data$投手[9]))
```

### 防御率

```{r}
gauge(pitp_data$防御率[9], min = 0, max = 5, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,2.010), warning = c(2.011,2.950), danger = c(2.951,99)
))
```

### FIP

```{r}
gauge(pitp_data$FIP[9], min = 0, max = 5,  abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,2.707), warning = c(2.708,3.019), danger = c(3.02,99)
))
```

### BABIP

```{r}
gauge(pitp_data$BABIP[9], min = 0, max = 0.5, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,0.265), warning = c(0.266,0.277), danger = c(0.278,99)
))
```

### K9

```{r}
gauge(pitp_data$K9[9], min = 0, max = 20, abbreviateDecimals = 3, 
      gaugeSectors(success = c(6.958,99), warning = c(6.504,6.957), danger = c(0,6.503)
))
```

### BB9

```{r}
gauge(pitp_data$BB9[9], min = 0, max = 5, abbreviateDecimals = 2, 
      gaugeSectors(success = c(0,1.824), warning = c(1.825,2.623), danger = c(2.624,99)
))
```

### HR9

```{r}
gauge(pitp_data$HR9[9], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0,0.438), warning = c(0.439,0.551), danger = c(0.552,99)
))
```

### H9

```{r}
gauge(pitp_data$H9[9], min = 0, max = 15, abbreviateDecimals = 2, 
      gaugeSectors(success = c(0,7.592), warning = c(7.593,7.869), danger = c(7.870,99)
))
```

### LOB

```{r}
gauge(pitp_data$LOB[9], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0.761,99), warning = c(0.752,0.760), danger = c(0,0.751)
))
```

### K-BB%

```{r}
gauge(pitp_data$`K-BB%`[9], min = 0, max = 1, abbreviateDecimals = 3, 
      gaugeSectors(success = c(0.145,99), warning = c(0.110,0.144), danger = c(0,0.109)
))
```

------------------------------------------------------------------------