---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    navbar:
      - { title: "Home", href: "https://hokmts23.netlify.app/"}
    social: [ "twitter","menu"]
---

```{r setup, include=FALSE}
library(flexdashboard)
library("rvest")
library("dplyr")
library("tidyverse")
library("openxlsx")
library("ggplot2")
library("patchwork")
library("knitr")
library("kableExtra")
library("tidyverse")
library("cowplot")
library("gridExtra")
library("gganimate")
#library("transformr")
library("gifski")
library("gt")
library("DT")
library("readxl")
# data load & pacific central data merge
batc_data<-  read_xlsx("~/Public/baseball/2022/02data/02league/bat_c_2022cl.xlsx",
                        sheet = 'Sheet1')
```

row
-----------------------------------------------------------------------

### player

```{r}
valueBox(paste(batc_data$選手[1]))
```

### 打率

```{r}
gauge(batc_data$打率, min = 0, max = 0.4, abbreviateDecimals = 3,
      gaugeSectors(success = c(0.25,999), warning = c(0.2,0.24), danger = c(0,0.19)
))
```

### ops

```{r}
gauge(batc_data$ops, min = 0, max = 1.5, abbreviateDecimals = 3,
      gaugeSectors(success = c(0.8,99), warning = c(0.5,0.7), danger = c(0,0.4)
))
```


### Iso

```{r}
gauge(batc_data$Iso, min = 0, max = 0.5, abbreviateDecimals = 3,
      gaugeSectors(success = c(0.3,99), warning = c(0.2,0.29), danger = c(0,0.1)
))
```



### HR%

```{r}
gauge(round(batc_data$`HR%`*100,3), min = 0, max = 10,
      abbreviateDecimals = 3, symbol = '%',
      gaugeSectors(success = c(0.05,99), warning = c(0.02,0.04), danger = c(0,0.01)
))
```

### K%

```{r}
gauge(round(batc_data$`K%`*100,3), min = 0, max = 30, 
      abbreviateDecimals = 2, symbol = '%',
      gaugeSectors(success = c(0,10), warning = c(11,19), danger = c(20,99)
))
```

### BB%

```{r}
gauge(round(batc_data$`BB%`*100,4), min = 0, max = 30, 
      abbreviateDecimals = 2, symbol = '%',
      gaugeSectors(success = c(21,99), warning = c(10,20), danger = c(0,9)
))
```

### wOBA

```{r}
gauge(batc_data$wOBA, min = 0, max = 1, 
      abbreviateDecimals = 3, 
      gaugeSectors(success = c(0.5,99), warning = c(0.3,0.4), danger = c(0,0.2)
))
```


### wRAA

```{r}
gauge(batc_data$wRAA, min = 0, max = 100, gaugeSectors(
  success = c(50,99), warning = c(21,49), danger = c(0,20)
))
```

### wRC

```{r}
gauge(batc_data$wRC, min = 0, max = 200, 
      gaugeSectors(success = c(150,999), warning = c(100,149), danger = c(0,99)
))
```

### wRC+

```{r}
gauge(round(batc_data$`wRC+`*100,2), min = 0, max = 200, 
      gaugeSectors(success = c(150,999), warning = c(100,149), danger = c(0,99)
))
```

-----------------------------------------------------------------------
